- name: Play1
  hosts: all
  tasks:
    - name: Printing hello
      ansible.builtin.debug:
        msg: Hello from task2

- name: Play 2
  hosts: dev
  tasks:
    - name: Printing hello 2
      ansible.builtin.debug:
      msg: Hello from task 2


# - name: Play1  
#   hosts: all 
#   tasks: 
#     - name: Printing hello from task1 of play1  
#       ansible.builtin.debug:
#         msg: Hello from task1  