- name: Demo on using variables
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - demo-vars.yaml 
  vars_prompt:
    - name: URL
      prompt: Enter URL Value
      private: false
  tasks:
    - name: Printing the value of URL
      ansible.builtin.debug:
        msg: "{{URL}}"

    - name: Printing the value of URL
      ansible.builtin.debug:
        msg: The value of URL is {{URL}}
      vars: 
        URL: facebook.com

    - name: Printing the value of NULL 
      ansible.builtin.debug:
        msg: The value of URL is "{{CLI_URL}}"
      

