- name: Demo on using variables
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: Printing the value of URL
      ansible.builtin.debug:
        msg: "{{URL}}"
        
    - name: Printing the value of URL
      ansible.builtin.debug:
        msg: The value of URL is "{URL}"

