- name: Demo on facts
  hosts: all
  tasks:
    - name: task 1
      ansible.builtin.debug:
        msg: OS Distribution = {{ansible_distribution_file_path}}
    
    - name: task 2 
      ansible.builtin.debug:
        msg: MAC address of all hosts = {{macaddress}}