- name: Demo on facts
  hosts: all
  tasks:
    - name: task 1
      ansible.builtin.debug:
        msg: OS Distribution = {{ansible_distribution_file_path}}
    
    - name: task 2 
      ansible.builtin.debug:
        msg: IP address of all hosts = {{ansible_default_ipv4.address}}
        msg: Macaddress of all hosts = {{ansible_default_ipv4.macaddress}}