- name: Shell module
  hosts: all
  tasks:
    - name: task1
      ansible.builtin.shell: uptime
      register: OUT  # register captures the output command and preserers in variable name of out choice
      
    - name: task2
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"

    - name: task3
      ansible.builtin.set_fact:
        STATUS: "{{OUT.rc}}"

    - name: Printing exit code
      ansible.builtin.debug:
        msg: "{{STATUS}}"

    - name: Execute the ps command
      ansible.builtin.shell: ps -ef| grep jenkins

    - name: Print the status of ps command
      ansible.builtin.debug:
        msg: Hai
