- name: Shell module
  hosts: all
  tasks:
    - name: task1
      ansible.builtin.shell: uptime
      register: OUT  # register captures the output command and preserers in variable name of out choice
        msg: 
          - Uptime is {{OUT}}