- name: Demo on using conditions
  hosts: all
  vars:
    actions: true
  tasks:
    - name: Run this command on centos machines
      ansible.builtin.debug:
        msg: Hi I am centos
      when: ansible_distribution == "Centos"

    - name: Run this command on Ubuntu machines
      ansible.builtin.debug:
        msg: Hi I am centos
      when:  ansible_distribution == "Ubuntu"
      
    - name: Run this action
      ansible.builtin.debug:
        msg: I will only run when action is true
      when: actions