- name: Demo on loops
  hosts: prod
  tasks:
    - name: Printing a loop
      ansible.builtin.debug:
        msg: Value in the loop is {{item}}
      loop:
        - 10
        - 20
        - 30
        - 40
        - 50